- name: This playbook will install,configure and deploy webpages in the nginx web server 
  hosts: all 
  vars:
     greeting_message: "DevOps"
     automation_tool: "Ansible"
     provisioner_tool: "Docker"
     proxy_conf: 
        http_proxy: http://genproxy.corp.amdocs.com:8080 
        https_proxy: https://genproxy.corp.amdocs.com:8080 
  tasks: 
    - name: Insatll nginx on ubuntu 
      apt: name=nginx state=latest update_cache=yes 
      environment: "{{proxy_conf}}" 
      when: ( ansible_distribution == "Ubuntu" and  ansible_os_family == "Debian" ) 

    - name: Create the web root folder
      file: path=/var/html state=directory mode=0777
 
    - name: configure nginx in ubuntu 
      copy: src=default dest=/etc/nginx/sites-available/default 
      when: ( ansible_distribution == "Ubuntu" and  ansible_os_family == "Debian" ) 

    - name: Deploy Our custome web page
      template: src=index.html.j2 dest=/var/html/index.html

    - name: start nginx in ubuntu 
      shell:  "service nginx restart"
      when: ( ansible_distribution == "Ubuntu" and  ansible_os_family == "Debian" )
